services:
  mailbot:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: mailbot
    working_dir: /api
    env_file:
      - .env
    volumes:
      - .:/api
    command: ["dotnet", "watch", "run"]
    ports:
      - "5156:5156"
    restart: unless-stopped
